# CI File for building and deploying the frontend and backend for kaleidoscope.
# This deployment expects the following aws settings to be provided implicitly.
# (via project CI settings external to this file):
# $AWS_ACCESS_KEY_ID
# $AWS_SECRET_ACCESS_KEY
# $AWS_DEFAULT_REGION

# AWS Access should be an IAM role with permission required to deploy and make changes via cloudformation (CF, S3, Lambda, etc)

image: busybox:latest

before_script:
  - echo "Beginning Build/Deploy of Kaleidoscope"

after_script:
  - echo "Completed Build/Deploy"

stages:
  - infra-apply
  - build
  - deploy

Terraform Apply:
  stage: infra-apply
  only:
    - master
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  variables:
    AWS_ACCESS_KEY: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: $AWS_REGION
  before_script:
    - cd terraform
  script:
    - terraform init
    - terraform apply --auto-approve
  dependencies: [ ]

Build:
  stage: build
  only:
    - master
  image: node:15.12.0-alpine3.10
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/kaleidoscope-frontend
  dependencies:
    - Terraform Apply

Deploy Site:
  stage: deploy
  only:
    - master
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  variables:
    AWS_ACCESS_KEY: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - aws s3 sync dist/kaleidoscope-frontend s3://kaleidoscope.alexlbates.com --delete
  dependencies:
    - Build
