# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

variables:
  AWS_ACCESS_KEY_ID: '$AWS_ACCESS_KEY_ID'
  AWS_SECRET_ACCESS_KEY: '$AWS_SECRET_ACCESS_KEY'
  AWS_REGION: 'AWS_DEFAULT_REGION'
  STACK_NAME_FRONTEND: 'kaleidoscope-frontend'
  STACK_NAME_MEDIA: 'kaleidoscope-media'


image: busybox:latest

before_script:
  - echo "Beginning Build/Deploy of Kaleidoscope-Combined"

after_script:
  - echo "Completed Build/Deploy"
#
#deploy1:
#  stage: deploy
#  script:
#    - docker-compose --env-file .env.prod up -d --build
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "master"'
#      when: always

build2:
  stage: build
  image: node:current-alpine3.10
  script:
    - cd frontend
    - npm ci
    - npm run-script build
  artifacts:
    paths:
      - frontend/dist/kaleidoscope-frontend


deploy2:
  stage: deploy
  image: python:latest
  before_script:
    - pip install awscli
  script:
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file ./media-storage.cft.yml --stack-name $STACK_NAME_MEDIA
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file ./frontend-deploy.cft.yml --stack-name $STACK_NAME_FRONTEND #credentials implicit via global variables???
    - aws s3 cp frontend/dist/kaleidoscope-frontend/ s3://${$STACK_NAME_FRONTEND} --recursive --acl public-read
  needs:
    - build2
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
