# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# CI File for building and deploying the frontend and backend for kaleidoscope.
# This deployment expects the following aws settings to be provided implicitly.
# (via project CI settings external to this file):
# $AWS_ACCESS_KEY_ID
# $AWS_SECRET_ACCESS_KEY
# $AWS_DEFAULT_REGION

# AWS Access should be an IAM role with permission required to deploy and make changes via cloudformation (CF, S3, Lambda, etc)

image: busybox:latest

variables:
  STACK_NAME_FRONTEND: 'kaleidoscope-frontend'
  STACK_NAME_MEDIA: 'kaleidoscope-media'

before_script:
  - echo "Beginning Build/Deploy of Kaleidoscope-Combined"

after_script:
  - echo "Completed Build/Deploy"
#this is the old school. we trying to get to the new school.
#deploy1:
#  stage: deploy
#  script:
#    - docker-compose --env-file .env.prod up -d --build
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "master"'
#      when: always

build2:
  stage: build
  image: node:15.12.0-alpine3.10
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist/kaleidoscope-frontend

deploy2:
  stage: deploy
  image: python:latest
  before_script:
    - pip install awscli
  script:
    - echo "Attempting to build S3 bucket for media storage"
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file ./aws-architecture/media-storage.cft.yml --stack-name $STACK_NAME_MEDIA
    - echo "Completed media storage bucket creation/update"

    - echo "Attempting to build S3 bucket for frontend website serving"
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file ./aws-architecture/frontend-deploy.cft.yml --stack-name $STACK_NAME_FRONTEND #credentials implicit via global variables???
    - echo "Completed build/update for website"

    - echo "Moving frontend files to S3 bucket"
    - aws s3 cp frontend/dist/kaleidoscope-frontend/ s3://${STACK_NAME_FRONTEND} --recursive --acl public-read
    - echo "Completed copy of frontend files"


  needs:
    - build2
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
