# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# CI File for building and deploying the frontend and backend for kaleidoscope.
# This deployment expects the following aws settings to be provided implicitly.
# (via project CI settings external to this file):
# $AWS_ACCESS_KEY_ID
# $AWS_SECRET_ACCESS_KEY
# $AWS_DEFAULT_REGION

# AWS Access should be an IAM role with permission required to deploy and make changes via cloudformation (CF, S3, Lambda, etc)

image: busybox:latest

variables:
  STACK_NAME_FRONTEND: 'kaleidoscope-frontend'
  STACK_NAME_MEDIA: 'kaleidoscope-media'

before_script:
  - echo "Beginning Build/Deploy of Kaleidoscope-Combined"

after_script:
  - echo "Completed Build/Deploy"
#this is the old school. we trying to get to the new school.
#deploy1:
#  stage: deploy
#  script:
#    - docker-compose --env-file .env.prod up -d --build
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "master"'
#      when: always

build2:
  stage: build
  image: maven:3.6.3-jdk-11
  before_script:
    - >
      sudo apt-get install -y git-core curl build-essential openssl libssl-dev \
      && git clone https://github.com/nodejs/node.git \
      && cd node \
      && ./configure \
      && make \
      && sudo make install
  script:
    - cd frontend
    - npm ci
    - cd ../
    - npm --prefix ./frontend run build
    - mkdir -p ./kaleidoscope-backend/src/main/resources/static # static dir is empty in git, so folder doesnt exist by default.
    - cp ./frontend/dist/kaleidoscope-frontend/* ./kaleidoscope-backend/src/main/resources/static
    - mvn -f kaleidoscope-backend/ package
  artifacts:
    paths:
      - frontend/dist/kaleidoscope-frontend
      - kaleidoscope-backend/target

deploy2:
  stage: deploy
  image: python:latest
  before_script:
    - pip install awscli
    - pip install awsebcli
  script:
    - echo "Attempting to build S3 bucket for media storage"
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file ./aws-architecture/media-storage.cft.yml --stack-name $STACK_NAME_MEDIA
    - echo "Completed media storage bucket creation/update"


    - echo "Attempting to EB Deploy"
    - cd kaleidoscope-backend
    - eb deploy
    - echo "EB Deploy Complete"

#    - echo "Attempting to build S3 bucket for frontend website serving"
#    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file ./aws-architecture/frontend-deploy.cft.yml --stack-name $STACK_NAME_FRONTEND #credentials implicit via global variables???
#    - echo "Completed build/update for website"

#    - echo "Moving frontend files to S3 bucket"
#    - aws s3 cp frontend/dist/kaleidoscope-frontend/ s3://${STACK_NAME_FRONTEND} --recursive --acl public-read
#    - echo "Completed copy of frontend files"


  needs:
    - build2
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
