version: "3.3"
services:
  frontend:
    build: "./frontend"
    restart: always
    environment:
      - TEST=1
    ports:
      - "${FRONTEND_PORT:-80}:80"
  backend:
    build: "./kaleidoscope-backend"
    restart: always
    environment:
      - PORT=${BACKEND_PORT:-7000}
      - IMAGE_DIRECTORY=/media/kaleidoscope
#      - FILE_INFO_PATH=/media/songmeta.json
    ports:
      - "${BACKEND_PORT:-7000}:7000"
    volumes:
      - ${MEDIA_VOL:-~/projects/wsg_scraper/image_pool}:/media/kaleidoscope/
      - ${META_FILE:-~/projects/kaleidoscope/songmeta.json}:/media/songmeta.json
