openapi: 3.0.0
info:
  title: Kaleidoscope Backend
  description: Kaleidoscope project backend. Glorified File Server.
  version: 1.0.0
tags:
  - name: tag1
    description: placeholder
paths:
  '/example/{val}':
    get:
      summary: example summary
      description: example description
      tags: ['tag1']
      parameters:
        - in: path
          name: val
          schema:
            type: integer
            format: int64
          required: true
          description: this is an example param
      responses:
        '200':
          description: good to go