#https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-s3.html
AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    3877c396-710b-4c4d-897e-3932a42d75ed:
      size:
        width: 60
        height: 60
      position:
        x: 430
        'y': 160
      z: 0
      embeds: []
Parameters:
  BucketNamed:
    Type: String
    Default: www.alexlbates.com
    Description: name for created s3 bucket.
Resources:
  FrontendBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketNamed
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3877c396-710b-4c4d-897e-3932a42d75ed
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - FrontendBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - FrontendBucket
          - DomainName
    Description: Name of S3 bucket to hold website content
